services:
  # mongo database
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test_pass

  # mongo-express
  mongo-express:
    image: mongo-express
    restart: always
  # node app
  node-app:
    depends_on:
      - mongo
    build: .

volumes:
  mongo-db:
