
# load balancer
upstream node_app {
  least_conn;
  # load balancing algorithm, send to the server with the least connection.
  server node-app:5000; 
  # in docker you assign the service name directly not the server ip.
  # add more server lines for more apps 
}

# routing
server {
    listen 80;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";


    location / {
      proxy_pass http://node_app:5000;  
      # must be the upstream the name 
      proxy_redirect off;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
  }
}
