services:
  nginx-server:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/conf.d/defaut.conf

  node-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - nginx-server
